"""fix the relationships for the pilecontent table

Revision ID: 07cd9dae94a6
Revises: 58f797d0336f
Create Date: 2026-03-24 13:20:22.142249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07cd9dae94a6'
down_revision: Union[str, Sequence[str], None] = '58f797d0336f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
