"""add position for cards

Revision ID: 58f797d0336f
Revises: 6ec58f21fc3a
Create Date: 2026-03-23 22:40:00.587392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f797d0336f'
down_revision: Union[str, Sequence[str], None] = '6ec58f21fc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'card_position')
    # ### end Alembic commands ###
