"""add_name_birthday_zodic

Revision ID: 9645a86d1ac5
Revises: 36ca5a5c1980
Create Date: 2026-03-21 20:34:59.351595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9645a86d1ac5'
down_revision: Union[str, Sequence[str], None] = '36ca5a5c1980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('zodiac_sign', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zodiac_sign')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
